opt_in_rules:
 - sorted_imports

disabled_rules:
 - void_function_in_ternary
 - todo
 
line_length:
  warning: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
